spring.application.name=superagent-api

# Database Configuration (PostgreSQL)
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/baymax}
spring.datasource.username=${DATABASE_USER:postgres}
spring.datasource.password=${DATABASE_PASS:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
